#  services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: dokernodejs
  labels:
    app: dokernodejs
spec:
  type: LoadBalancer
  ports:
  - port: 8099
    name: http
  selector:
    app: dokernodejs
---
apiVersion: apps/v1  #TODONE: Migrated to apps/v1 from extensions/v1beta1
kind: Deployment
metadata:
  name: dokernodejs-v1
spec:
  replicas: 3
  minReadySeconds: 10 # Wait 2 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1 # When updating never have more than one extra pod. If replicas = 2 then never 3 pods when updating
  template:
    metadata:
      labels:
        app: dokernodejs
        version: v1
    spec:
      containers:
      - name: dokernodejs
        image: mikedodaro/dockernodejs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8099
---
