---
# vs-webapplication1 services
##################################################################################################
apiVersion: latest
kind: Service
metadata:
  name: webapplication2
  labels:
    app: webapplication2
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    name: http
  selector:
    app: webapplication2
---
apiVersion: extensions/latest  #TODO: Migrate to apps/v1
kind: Deployment
metadata:
  name: webapplication2
spec:
  replicas: 3
  minReadySeconds: 10 # Wait 2 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1 # When updating never have more than one extra pod. If replicas = 2 then never 3 pods when updating
  template:
    metadata:
      labels:
        app: webapplication2
        version: latest
    spec:
      containers:
      - name: webapplication2
        image: mikedodaro/webapplication2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8098
---
